### ISSUE TITLE
Footnote support

### ISSUE THREAD

**Issue by julianmichael** [julianmichael/nlp-off-the-record#3]
Idk what this looks like in Jekyll. May be super easy. But it'd be nice to have support for footnotes either at the bottom, or floating along the side (collapsing in responsively or whatever).

**Comment by jkkummerfeld** [comment]
Turns out there is built in support. For full details see - https://kramdown.gettalong.org/syntax.html#footnotes

For example:

```
This is some text.[^any-text-in-label]. Other text.[^another].

[^any-text-in-label]: Write the definition wherever you like. It will appear at the end of the doc
[^another]: Other def

Blah Blah
```

Would make:

This is some text.^1. Other text.^2

Blah Blah


1: Write the definition wherever you like. It will appear at the end of the doc
2: Other def

**Comment by julianmichael** [comment]
Nice. Tried it and it works nicely. Slightly annoying that we can't straightforwardly control where to put the footnotes (seems we'd have to do this indirectly by how we structure the layout files) but certainly good enough. Thanks!
